// Copyright © Citrix Systems, Inc.  All rights reserved.

export const XAXD_STATUS_REQUEST_DATA = 'XAXD_STATUS_REQUEST_DATA';
export const XAXD_STATUS_RECEIVE_DATA = 'XAXD_STATUS_RECEIVE_DATA';
export const XAXD_STATUS_LICENSE_SERVER_TYPE_CHANGED = 'XAXD_STATUS_LICENSE_SERVER_TYPE_CHANGED';