// Copyright © Citrix Systems, Inc.  All rights reserved.

export const CPSM_CUSTOMER_REQUEST_DATA = 'CPSM_CUSTOMER_REQUEST_DATA';
export const CPSM_CUSTOMER_RECEIVE_DATA = 'CPSM_CUSTOMER_RECEIVE_DATA';
export const CPSM_CUSTOMER_REQUEST_ROW_DETAIL = 'CPSM_CUSTOMER_REQUEST_ROW_DETAIL';
export const CPSM_CUSTOMER_RECEIVE_ROW_DETAIL = 'CPSM_CUSTOMER_RECEIVE_ROW_DETAIL';