// Copyright © Citrix Systems, Inc.  All rights reserved.

export const XAXD_USAGE_SORT = 'XAXD_USAGE_SORT';
export const XAXD_USAGE_REQUEST_DATA = 'XAXD_USAGE_REQUEST_DATA';
export const XAXD_USAGE_REQUEST_EXPORT = 'XAXD_USAGE_REQUEST_EXPORT';
export const XAXD_USAGE_RECEIVE_DATA = 'XAXD_USAGE_RECEIVE_DATA';
export const XAXD_USAGE_RECEIVE_EXPORT = 'XAXD_USAGE_RECEIVE_EXPORT';