// Copyright © Citrix Systems, Inc.  All rights reserved.

export const CPSM_SERVICE_REQUEST_DATA = 'CPSM_SERVICE_REQUEST_DATA';
export const CPSM_SERVICE_RECEIVE_DATA = 'CPSM_SERVICE_RECEIVE_DATA';
export const CPSM_SERVICE_REQUEST_ROW_DETAIL = 'CPSM_SERVICE_REQUEST_ROW_DETAIL';
export const CPSM_SERVICE_RECEIVE_ROW_DETAIL = 'CPSM_SERVICE_RECEIVE_ROW_DETAIL';