// Copyright © Citrix Systems, Inc.  All rights reserved.

export const NETSCALER_ALLOCATED_CHANGE_FILTER = 'NETSCALER_ALLOCATED_CHANGE_FILTER';
export const NETSCALER_ALLOCATED_EXPORT_CSV = 'NETSCALER_ALLOCATED_EXPORT_CSV';
export const NETSCALER_ALLOCATED_REQUEST_DATA = 'NETSCALER_ALLOCATED_REQUEST_DATA';
export const NETSCALER_ALLOCATED_RECEIVE_DATA = 'NETSCALER_ALLOCATED_RECEIVE_DATA';
export const NETSCALER_ALLOCATED_SORT = 'NETSCALER_ALLOCATED_SORT';